-- MySQL Script generated by MySQL Workbench
-- 01/01/16 20:25:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`utilizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilizador` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` ENUM('cliente', 'funcionario') NOT NULL DEFAULT 'cliente' COMMENT '',
  `nome` VARCHAR(500) NOT NULL COMMENT '',
  `contribuinte` INT UNSIGNED NOT NULL COMMENT '',
  `data_nascimento` DATE NOT NULL COMMENT '',
  `morada` VARCHAR(500) NULL COMMENT '',
  `numero_reservas` INT NOT NULL DEFAULT 0 COMMENT '',
  `palavraPasse` VARCHAR(20) NOT NULL COMMENT '',
  `telefone` INT UNSIGNED NOT NULL COMMENT '',
  `email` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `contribuinte`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` ENUM('dinheiro', 'credito', 'transferencia') NOT NULL COMMENT '',
  `hora` TIME(3) NOT NULL COMMENT '',
  `data` DATE NOT NULL COMMENT '',
  `montante` FLOAT UNSIGNED NOT NULL COMMENT '',
  `cliente_id` INT UNSIGNED NOT NULL COMMENT '',
  `cliente_contribuinte` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `cliente_id`, `cliente_contribuinte`)  COMMENT '',
  INDEX `fk_pagamento_cliente_idx` (`cliente_id` ASC, `cliente_contribuinte` ASC)  COMMENT '',
  CONSTRAINT `fk_pagamento_cliente`
    FOREIGN KEY (`cliente_id` , `cliente_contribuinte`)
    REFERENCES `mydb`.`utilizador` (`id` , `contribuinte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`quarto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` ENUM('simples', 'duplo', 'suite') NOT NULL COMMENT '',
  `n_criancas` INT UNSIGNED NOT NULL COMMENT '',
  `n_adultos` INT UNSIGNED NOT NULL COMMENT '',
  `n_camas_casal` INT UNSIGNED NOT NULL COMMENT '',
  `n_camas_solteirro` INT UNSIGNED NOT NULL COMMENT '',
  `preco` FLOAT UNSIGNED NOT NULL COMMENT '',
  `ocupado` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `data_check_in` DATE NOT NULL COMMENT '',
  `data_check_out` DATE NOT NULL COMMENT '',
  `tipo_pensao` ENUM('sem', 'meia', 'completa') NOT NULL COMMENT '',
  `estado` ENUM('pendente', 'concluido') NOT NULL COMMENT '',
  `cliente_id` INT UNSIGNED NOT NULL COMMENT '',
  `cliente_contribuinte` INT UNSIGNED NOT NULL COMMENT '',
  `quarto_id` INT UNSIGNED NULL COMMENT '',
  PRIMARY KEY (`id`, `cliente_id`, `cliente_contribuinte`, `quarto_id`)  COMMENT '',
  INDEX `fk_reserva_cliente1_idx` (`cliente_id` ASC, `cliente_contribuinte` ASC)  COMMENT '',
  INDEX `fk_reserva_quarto1_idx` (`quarto_id` ASC)  COMMENT '',
  CONSTRAINT `fk_reserva_cliente1`
    FOREIGN KEY (`cliente_id` , `cliente_contribuinte`)
    REFERENCES `mydb`.`utilizador` (`id` , `contribuinte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_quarto1`
    FOREIGN KEY (`quarto_id`)
    REFERENCES `mydb`.`quarto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`utilizador`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`utilizador` (`id`, `tipo`, `nome`, `contribuinte`, `data_nascimento`, `morada`, `numero_reservas`, `palavraPasse`, `telefone`, `email`) VALUES (1, 'Cliente', 'Manuel', 215479548, '1986-04-23', 'Camacha', 1, '3dsad', 985462159, 'manuel@mail.com');
INSERT INTO `mydb`.`utilizador` (`id`, `tipo`, `nome`, `contribuinte`, `data_nascimento`, `morada`, `numero_reservas`, `palavraPasse`, `telefone`, `email`) VALUES (2, 'Funcionario', 'Maria', 256445889, '1990-11-09', 'Machico', 0, '4sasd4s', 976522321, 'maria@mail.com');
INSERT INTO `mydb`.`utilizador` (`id`, `tipo`, `nome`, `contribuinte`, `data_nascimento`, `morada`, `numero_reservas`, `palavraPasse`, `telefone`, `email`) VALUES (3, 'Cliente', 'João', 266988744, '1950-02-12', 'Santana', 2, 'as4d', 952263252, 'joao@mail.com');
INSERT INTO `mydb`.`utilizador` (`id`, `tipo`, `nome`, `contribuinte`, `data_nascimento`, `morada`, `numero_reservas`, `palavraPasse`, `telefone`, `email`) VALUES (4, 'Funcionario', 'Abel', 255448812, '1962-06-06', 'Calheta', 0, 'as3wd', 946522125, 'abel@mail.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`pagamento`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`pagamento` (`id`, `tipo`, `hora`, `data`, `montante`, `cliente_id`, `cliente_contribuinte`) VALUES (1, 'dinheiro', '20:30:10', '2015-12-28', 500, 1, 215479548);
INSERT INTO `mydb`.`pagamento` (`id`, `tipo`, `hora`, `data`, `montante`, `cliente_id`, `cliente_contribuinte`) VALUES (2, 'credito', '09:12:50', '2015-12-27', 130, 3, 266988744);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`quarto`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`quarto` (`id`, `tipo`, `n_criancas`, `n_adultos`, `n_camas_casal`, `n_camas_solteirro`, `preco`, `ocupado`) VALUES (1, 'suite', 5, 4, 2, 5, 534, true);
INSERT INTO `mydb`.`quarto` (`id`, `tipo`, `n_criancas`, `n_adultos`, `n_camas_casal`, `n_camas_solteirro`, `preco`, `ocupado`) VALUES (2, 'duplo', 2, 2, 1, 2, 250, false);
INSERT INTO `mydb`.`quarto` (`id`, `tipo`, `n_criancas`, `n_adultos`, `n_camas_casal`, `n_camas_solteirro`, `preco`, `ocupado`) VALUES (3, 'simples', 1, 2, 1, 0, 130, true);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`reserva`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`reserva` (`id`, `data_check_in`, `data_check_out`, `tipo_pensao`, `estado`, `cliente_id`, `cliente_contribuinte`, `quarto_id`) VALUES (1, '2015-08-10', '2015-08-15', 'completa', 'concluido', 1, 215479548, 2);
INSERT INTO `mydb`.`reserva` (`id`, `data_check_in`, `data_check_out`, `tipo_pensao`, `estado`, `cliente_id`, `cliente_contribuinte`, `quarto_id`) VALUES (2, '2015-12-28', '2016-01-02', 'meia', 'pendente', 3, 266988744, 1);
INSERT INTO `mydb`.`reserva` (`id`, `data_check_in`, `data_check_out`, `tipo_pensao`, `estado`, `cliente_id`, `cliente_contribuinte`, `quarto_id`) VALUES (3, '2015-12-31', '2016-01-02', 'sem', 'concluido', 4, 255448812, 3);

COMMIT;

